//
//  SymbolOption.swift
//  Linkeeper
//
//  Created by Om Chachad on 04/07/23.
//

import Foundation

enum SymbolCategory: String, CaseIterable {
    case objects = "Objects"
    case people = "People"
    case symbols = "Symbols"
    
    var symbolKeys: [String] {
        switch(self) {
        case .objects:
            return [
                "car.fill",
                "bus.fill",
                "bicycle",
                "airplane",
                "house.fill",
                "building.2.fill",
                "cart.fill",
                "bag.fill",
                "fork.knife",
                "takeoutbag.and.cup.and.straw.fill",
                "thermometer",
                "sun.max.fill",
                "moon.fill",
                "snowflake",
                "cloud.fill",
                "cloud.rain.fill",
                "umbrella.fill",
                "flame.fill",
                "binoculars.fill",
                "globe",
                "photo.fill",
                "camera.fill",
                "doc.on.clipboard.fill",
                "calendar",
                "envelope.fill",
                "paperplane.fill",
                "briefcase.fill",
                "folder.fill",
                "creditcard.fill",
                "phone.fill",
                "laptopcomputer",
                "desktopcomputer",
                "chart.bar.fill",
                "printer.fill",
                "archivebox.fill",
                "tv.fill",
                "gamecontroller.fill",
                "headphones",
                "music.note",
                "speaker.fill",
                "books.vertical.fill",
                "book.fill",
                "bookmark.fill",
                "eyeglasses",
                "ticket.fill",
                "dice.fill",
                "sportscourt.fill",
                "lifepreserver.fill",
                "hare.fill",
                "clock.fill",
                "alarm.fill",
                "stopwatch.fill",
                "bell.fill",
                "heart.fill",
                "star.fill",
                "lightbulb.fill",
                "bolt.fill",
                "flag.fill",
                "tag.fill",
                "key.fill",
                "hourglass",
                "lock.fill",
                "battery.100",
                "wand.and.rays",
                "paintbrush.fill",
                "pencil",
                "scissors",
                "magnifyingglass",
                "link",
                "hammer.fill",
                "wrench.fill",
                "gear",
                "trash.fill",
                "cup.and.saucer.fill",
                "tshirt.fill",
                "bandage.fill",
                "stethoscope",
                "facemask.fill",
                "atom",
                "graduationcap.fill",
                "gift.fill",
                "bed.double.fill",
                "map.fill",
                "speedometer",
                "barometer",
                "network",
                "rectangle.split.2x1",
                "photo.fill.on.rectangle.fill",
                "camera.aperture",
                "arrow.up.circle.fill",
                "plus.bubble.fill",
                "square.fill",
                "hand.point.up.braille.fill",
                "square.and.arrow.down.fill",
                "square.and.arrow.up.fill",
                "play.circle.fill",
                "questionmark.circle.fill",
                "checkmark.circle.fill",
                "plus.circle.fill",
                "info.circle.fill",
                "xmark.square",
                "doc.text.fill",
                "square.grid.2x2.fill",
                "ellipsis",
                "list.bullet",
                "checklist",
                "rays",
                "infinity",
                "location.fill",
                "mappin.and.ellipse",
                "crop",
                "shuffle",
                "quote.bubble.fill",
                "camera.filters",
                "wifi",
                "airplayaudio",
                "airplayvideo",
                "music.note.list",
                "timer",
                "square.and.pencil",
                "dial.min.fill",
                "dial.max.fill",
                "wallet.pass.fill"
            ]
        case .people:
            return [
                "figure.stand",
                "person.fill",
                "person.2.fill",
                "person.3.fill",
                "person.crop.square.filled.and.at.rectangle.fill",
                "figure.walk",
                "figure.roll",
                "face.smiling.inverse",
                "figure.outdoor.cycle",
                "figure.yoga",
                "eye.fill",
                "eyes.inverse",
                "eyebrow",
                "nose.fill",
                "mustache.fill",
                "mouth.fill",
                "brain",
                "ear.fill",
                "hand.raised.fill",
                "hand.thumbsup.fill",
                "hand.thumbsdown.fill",
                "hands.clap.fill"
            ]
        case .symbols:
            return [
                "square.2.layers.3d.top.filled",
                "exclamationmark.triangle.fill",
                "arrowshape.turn.up.backward.fill",
                "arrowshape.turn.up.forward.fill",
                "barcode",
                "qrcode",
                "qrcode.viewfinder",
                "play.fill",
                "square",
                "chevron.backward.circle.fill",
                "chevron.right.circle.fill",
                "chevron.up.circle.fill",
                "chevron.down.circle.fill",
                "backward.circle.fill",
                "power.circle.fill",
                "stop.circle.fill",
                "forward.circle.fill",
                "doc",
                "dollarsign.circle.fill",
                "eurosign.circle.fill",
                "sterlingsign.circle.fill",
                "yensign.circle.fill",
                "bitcoinsign.circle.fill",
                "multiply.circle.fill",
                "staroflife",
                "doc.text",
                "doc.richtext",
                "square.grid.4x3.fill",
                "point.3.filled.connected.trianglepath.dotted",
                "arrow.3.trianglepath",
                "circle.circle",
                "arrow.down.right.and.arrow.up.left",
                "arrow.up.and.down.and.arrow.left.and.right",
                "arrow.2.squarepath",
                "arrow.triangle.2.circlepath",
                "slider.horizontal.3",
                "peacesign",
                "character.textbox",
                "pills.fill",
                "dot.radiowaves.forward",
                "dot.radiowaves.up.forward",
                "arrow.triangle.turn.up.right.diamond.fill",
                "arrow.triangle.turn.up.right.circle.fill",
                "waveform.path",
                "waveform",
                "calendar.badge.plus",
                "calendar.badge.exclamationmark",
                "timer.square",
                "plus.square.fill.on.square.fill",
                "camera.viewfinder",
                "nosign",
                "command.circle.fill"
            ]
        }
    }
    
    var symbolValues: [String] {
        switch(self) {
        case .objects:
            return [
                "Car",
                "Bus",
                "Bicycle",
                "Airplane",
                "House",
                "Building",
                "Cart",
                "Bag",
                "Cutlery",
                "Takeout Bag",
                "Thermometer",
                "Sun",
                "Moon",
                "Snowflake",
                "Cloud",
                "Rain Cloud",
                "Umbrella",
                "Flame",
                "Binoculars",
                "Globe",
                "Photo",
                "Camera",
                "Clipboard",
                "Calendar",
                "Envelope",
                "Paper Plane",
                "Briefcase",
                "Folder",
                "Credit Card",
                "Phone",
                "Laptop",
                "Desktop Computer",
                "Bar Chart",
                "Printer",
                "Archive Box",
                "TV",
                "Game Controller",
                "Headphones",
                "Music Note",
                "Speaker",
                "Books",
                "Book",
                "Bookmark",
                "Eyeglasses",
                "Ticket",
                "Dice",
                "Sports Court",
                "Life Preserver",
                "Hare",
                "Clock",
                "Alarm Clock",
                "Stopwatch",
                "Bell",
                "Heart",
                "Star",
                "Lightbulb",
                "Bolt",
                "Flag",
                "Tag",
                "Key",
                "Hourglass",
                "Lock",
                "Battery",
                "Wand",
                "Paintbrush",
                "Pencil",
                "Scissors",
                "Magnifying Glass",
                "Link",
                "Hammer",
                "Wrench",
                "Gear",
                "Trash",
                "Cup and Saucer",
                "T-Shirt",
                "Bandage",
                "Stethoscope",
                "Face Mask",
                "Atom",
                "Graduation Cap",
                "Gift",
                "Double Bed",
                "Map",
                "Speedometer",
                "Barometer",
                "Network",
                "Rectangle",
                "Photo",
                "Camera Aperture",
                "Up Arrow",
                "Plus",
                "Square",
                "Hand Pointing Up",
                "Square with Down Arrow",
                "Square with Up Arrow",
                "Play",
                "Question Mark",
                "Checkmark",
                "Plus Circle",
                "Info Circle",
                "X Mark Square",
                "Document",
                "Grid",
                "Ellipsis",
                "Bullet List",
                "Checklist",
                "Rays",
                "Infinity",
                "Location",
                "Map Pin",
                "Crop",
                "Shuffle",
                "Quote Bubble",
                "Camera Filters",
                "Wi-Fi",
                "AirPlay Audio",
                "AirPlay Video",
                "Music Note List",
                "Timer",
                "Square with Pencil",
                "Min",
                "Max",
                "Wallet Pass"
            ]
        case .people:
            return [
                "Figure Stand",
                "Person",
                "Person",
                "Person",
                "Person",
                "Figure Walk",
                "Figure Roll",
                "Smiling Face",
                "Outdoor Cycle",
                "Yoga",
                "Eye",
                "Eyes",
                "Eyebrow",
                "Nose",
                "Mustache",
                "Mouth",
                "Brain",
                "Ear",
                "Raised Hand",
                "Thumbs Up",
                "Thumbs Down",
                "Clapping Hands"
            ]
        case .symbols:
            return [
                "2-Layered Square",
                "Exclamation Triangle",
                "Turn Up Backward Arrow",
                "Turn Up Forward Arrow",
                "Barcode",
                "QR Code",
                "QR Code Viewfinder",
                "Play",
                "Square",
                "Backward Chevron Circle",
                "Right Chevron Circle",
                "Up Chevron Circle",
                "Down Chevron Circle",
                "Backward Circle",
                "Power Circle",
                "Stop Circle",
                "Forward Circle",
                "Document",
                "Dollar Sign Circle",
                "Euro Sign Circle",
                "Sterling Sign Circle",
                "Yen Sign Circle",
                "Bitcoin Sign Circle",
                "Multiply Circle",
                "Star of Life",
                "Text Document",
                "Rich Text Document",
                "4x3 Grid Square",
                "Dotted Triangle Path",
                "Triangle Path",
                "Circle Circle",
                "Down Right and Up Left Arrow",
                "Up and Down, Left and Right Arrows",
                "2 Square Path Arrow",
                "2 Circle Path Arrow",
                "Horizontal Slider",
                "Peace Sign",
                "Character Textbox",
                "Pills",
                "Dot Radiowaves Forward",
                "Dot Radiowaves Up Forward",
                "Diamond Arrow",
                "Circle Arrow",
                "Waveform Path",
                "Waveform",
                "Calendar Plus",
                "Calendar Exclamation",
                "Square Timer",
                "Plus Square on Square",
                "Camera Viewfinder",
                "No Sign",
                "Command Circle"
            ]
        }
    }
}
